### ISSUE TITLE
NOB will not plot if radar is in SAILS2 mode

### ISSUE THREAD

**Issue by sebenste** [Unidata/gempak#101]
NOB is not working when a radar is in SAILS2 mode. Otherwise it plots correctly, and base velocity plots correctly when the radar is in this mode.

**Comment by akrherz** [comment]
Can an example radar and scan time please be provided?

**Comment by sebenste** [comment]
Upon further review, this might actually be a "double compression" issue…we are investigating.

**Comment by akrherz** [comment]
@sebenste Yeah, I was going to suggest as much, but it would be good to be sure.

**Comment by sebenste** [comment]
Kevin reports:

Hi Gilbert,

I am convinced now the issues regarding the NIDS local radar data are when an office goes into SAILS or MRLE. Last night after 05Z I was watching the thunderstorms in South Dakota.  There were several offices that stopped showing radar data.  And it wasn't just me creating images for the webpage.  The radar data also did not show on NMAP2.  I looked at the data files and the data was there  (I was still getting radar files).  The N0B product was not showing an image however the N1B, the dual pol and velocity products still showed data.  The radar sites I looked at were ABR, FSD, LNX, UEX and TWX.  ABR was in SAILS2; FSD was in MRLE2, LNX was in SAILS3, and UEX and TWX were in SAILS1 I believe.  So it seems to me that there is some issue where SAILS and/or MRLE is causing a problem with the N0B product and not showing the data.  I have attached a couple images of what I was seeing and you can see on the colorbar how it is all messed up compared to a normal colorbar.  

So I hope this is able to help Daryl.  I think at the LNX site I was seeing a strobe or blinking effect after a certain time where one image would show then the next one would be blank. 

However, to make things more complicated, this morning Minneapolis is running SAILS 2 and I was not getting data (for the N0B product however, now I am seeing images get through.  So I am at a loss as to what is going on here.  At the very least, whenever a site is running SAILS or MRLE there seem to be issues for the lowest slice.  The other products seem to be coming in.   

That's all I have for now.

Kevin

----------------------
That sounds like the double compression issue. What do you think, and what would be a good fix?

**Comment by akrherz** [comment]
Yes, please ensure all files for N0B are running through Dan Vietors updated ucnids

**Comment by sebenste** [comment]
Do you happen to have a pqact entry with the script? I don't have either. Thanks!

**Comment by mzuranski** [comment]
@sebenste 
```
NEXRAD3	^SDUS[23578]. ([KPT])(...) ([0-3][0-9])([0-2][0-9])([0-5][0-9]).*/p(N[0-3]B)(...)
	PIPE	-close /home/ldm/util/ucnids -c - /home/data/level3/\7/\6/LATEST_\6
```
See attached for ucnids, last updated 2022-03-11
[ucnids.zip](https://github.com/Unidata/gempak/files/8892454/ucnids.zip)

**Comment by sebenste** [comment]
Thank you, Mike. Closing this ticket.
