### ISSUE TITLE
ENHANCEMENT: New lightning data

### ISSUE THREAD

**Issue by sebenste** [Unidata/gempak#104]
Will or can GEMPAK 7.15.1 plot this, and if so, how:

Users of the IDD NIMAGE feed products:

Reminder:

Tomorrow, Thursday, June 23, a new set of GLM composite products will
be added to the IDD NIMAGE feed.  The new GLM products are similar but
not identical to the GLM products that are currently being distributed
in the NIMAGE feed - see below for details on how the products differ.

Why are the new GLM images being added?

The grant that has funded the creation of the Texas Tech University
(TTU) GLM products is due to expire on July 21.  The new NOAA Virtual Lab
(Vlab) GLM products are intended to be a replacement for the TTU products.

What are the differences in the TTU and Vlab GLM products?

The Vlab products differ from the TTU products in several ways:

- the TTU products have GOES-East CONUS and FullDisk coverages while
 the Vlab products have GOES-East and GOES-West FullDisk coverages

- the TTU products contain Level2 fields while there are Level2 and
 Level3 fields in the Vlab products

 The TTU Level2 products contain 8 2-dimenstional fields:

   flash_extent_density
   flash_centroid_density
   average_flash_area
   total_energy
   group_extent_density
   group_centroid_density
   average_group_area
   minimum_flash_area

 The Vlab Level2 products contain 3 2-dimensional fields:

   Flash_extent_density
   Total_Optical_energy
   Minimum_flash_area

 and 6 1-dimensional fields of parallax corrected flash points:

   flash_lat
   flash_lon
   flash_area
   flash_energy
   flash_time
   flash_duration

 The Vlab Level2 fields represent 1-minute accumulations of the
 respective variable and are updated every minute.

 The Vlab Level3 products contain 3 2-dimensional fields:

   Flash_extent_density_w5u1
   Total_Optical_energy_w5u1
   Minimum_flash_area_w5u1

 The Vlab Level3 fields represent 5 minute averages of the respective
 variable and are updated every minute.

How can I differentiate the new Vlab products from the TTU products?

The LDM/IDD Product IDs for the TTU and Vlab products differ in the
directory portion of the product pathname which is used as the Product
ID, but not in the product name itself:

For example:

TTU FullDisk Level2 Product Id:

/data/ldm/pub/native/satellite/GOES/GOES16/Products/GeostationaryLightningMapper/FullDisk/20200122/OR_GLM-L2-GLMF-M3_G16_s20200222155000_e20200222156000_c20200222156450.nc

Vlab FullDisk Level2 Product Id:

/data/ldm/pub/native/satellite/GOES/GOES16/Products/GLMISatSS/Level2/FullDisk/20220617/OR_GLM-L2-GLMF-M6_G16_s20221682221000_e20221682222000_c20221682221300.nc

Vlab FullDisk Level3 Product Id:

/data/ldm/pub/native/satellite/GOES/GOES16/Products/GLMISatSS/Level3/FullDisk/20220617/OR_GLM-L3-GLMF-M6_G16_s20221682217000_e20221682222000_c20221682219300.nc

NOTE:

Since the product names for the Vlab and TTU products follow the GOES-R
ground station naming convention, one's LDM pattern-action file action(s)
that processes GLM products must differentiate between the TTU and Vlab
products using the directory component of the Product IDs.  Since the
Vlab products differ from the TTU products, it will be important to
write the products into separate areas on disk.

Please send any questions/comments about this addition to the IDD NIMAGE
feed to:

Unidata User Support <support@unidata.ucar.edu>

Best regards,

Unidata User Support
--
********************************************************************** <
Unidata User Support                              UCAR Unidata Program <
[(303)497-8643](tel:(303)497-8643)                                            P.O. Box 3000 <
support@unidata.ucar.edu                             Boulder, CO 80307 <
---------------------------------------------------------------------- <
Unidata Web Support               http://www.unidata.ucar.edu/support  <
********************************************************************** <

_______________________________________________
NOTE: All exchanges posted to Unidata maintained email lists are
recorded in the Unidata inquiry tracking system and made publicly
available through the web.  Users who post to any of the lists we
maintain are reminded to remove any personal information that they
do not want to be made public.

ldm-users mailing list
ldm-users@unidata.ucar.edu
For list information or to unsubscribe,  visit: https://www.unidata.ucar.edu/mailing_lists/

**Comment by mzuranski** [comment]
I believe what this would come down to is Gempak's ability to decode netCDf files.  While that's not something I've ever tried myself, I don't see a general netCDF decoder in the older [Gempak documentation](https://docs.unidata.ucar.edu/gempak/tutorial/gempak_programs.html#dc).  There are a few decoders for specific netCDF data ([dcncprof](https://docs.unidata.ucar.edu/gempak/man/prog/dcncprof.html), [dcacars](https://docs.unidata.ucar.edu/gempak/man/prog/dcacars.html), and [dcsuomi](https://docs.unidata.ucar.edu/gempak/man/prog/dcsuomi.html)), but I wouldn't expect those to work here.

In searching around this was the most related thing I found, it doesn't sound too encouraging but it's also 11 years old:  https://www.unidata.ucar.edu/support/help/MailArchives/gempak/msg05905.html

Another option might be to convert this data to GRIB2 format first, but that feels like an ugly hack.

**Comment by sebenste** [comment]
Thank you, Mike. OK, closing this ticket.
