### ISSUE TITLE
Support ECMWF raw files

### ISSUE THREAD

**Issue by sebenste** [Unidata/gempak#128]
Does/can/will GEMPAK 7.1* support ECMWF raw files for plotting?

Thanks!

Gilbert

**Comment by mzuranski** [comment]
ECMWF data is just grib2, maybe some small differences in variables but GEMPAK should be able to decode it like any other model.  Did you run into any problems or errors?

**Comment by sebenste** [comment]
No, just curious if the latest version can handle everything from the model in GRIB2 format. Thanks, Mike!
