### ISSUE TITLE
GEMPAK not compiling under Ubuntu 24.04.1 LTS

### ISSUE THREAD

**Issue by sebenste** [Unidata/gempak#154]
Hello everyone,

A buddy of mine, carefully following the instructions that Mike Zuranski made, cannot get GEMPAK to compile all the way through.

Using this to compile:

Makeinc.linux64_gfortran_ubuntu:

OPSYS = Linux

MCHSYS = MCHPRM.$(OPSYS)_gfortran

CC = gcc
FC = gfortran

MOTIFINC  = -I/usr/X11R6/include
XWINCDIR  = -I/usr/X11R6/include

COPT = -fno-stack-protector -DUNDERSCORE -D$(OPSYS) $(GEMINC) $(MOTIFINC) $(PYINC) $(WITHPY) -DG_64BIT -g -O2
FOPT = -fallow-invalid-boz -fallow-argument-mismatch -fno-stack-protector -fno-second-underscore -fno-range-check -fd-lines-as-comments $(GEMINC) $(PYINC) -g -O
NCII = "-I../libsrc"
NCOPT = "CPPFLAGS=-DNDEBUG -Df2cFortran -I$(OS_INC)" "FFLAGS=-O -Wno-globals" "CFLAGS=-O $(NCII)" "CXX= "
JASPEROPT = 'CC=$(CC)' 'CFLAGS=-O' '--disable-libjpeg'
XML2OPT = 'CC=$(CC)' '--with-iconv'
XMLDEP = -lpthread

CFLAGS = $(COPT)
CFLAGS_DB = $(COPT)
FFLAGS = $(FOPT)
LDM_FLAGS =

# Static OpenMotif
X11LIBDIR = -L/usr/X11R6/lib64
#MOTIFLIBS = $(X11LIBDIR) -Wl,-static -lXm -Wl,-Bdynamic -lXmu -lSM -lICE -lXp -lXext -lXft -ljpeg -lpng

# Dynamic OpenMotif
#X11LIBDIR = -L/usr/X11R6/lib -Wl,--rpath /usr/X11R6/lib
MOTIFLIBS = $(X11LIBDIR) -lXm

BUFRFLAGS = -O -DNO_MSG_IPC -ansi

SYSLIBS = $(PYLIB) $(PYDEP) -ldl
CSYSLIB = $(PYLIB) $(PYDEP)

He gets these errors:

/home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:38:(.text+0x50): undefined reference to `gg_init_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:71:(.text+0xf5): undefined reference to `gg_sdev_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:80:(.text+0x10a): undefined reference to `in_text_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:85:(.text+0x13d): undefined reference to `vwind_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:90:(.text+0x179): undefined reference to `in_outt_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:95:(.text+0x1be): undefined reference to `in_colr_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:96:(.text+0x1c9): undefined reference to `vad_colors_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:103:(.text+0x22f): undefined reference to `in_line_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:105:(.text+0x25c): undefined reference to `vad_line_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:93:(.text+0x300): undefined reference to `im_nids_output_luns_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:140:(.text+0x334): undefined reference to `im_cbar_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:147:(.text+0x395): undefined reference to `gg_map_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:148:(.text+0x3aa): undefined reference to `gg_ltln_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:154:(.text+0x3e8): undefined reference to `in_titl_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:170:(.text+0x42d): undefined reference to `vad_rms_colors_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:171:(.text+0x445): undefined reference to `vad_rms_vals_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:123:(.text+0x56c): undefined reference to `gg_maps_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:133:(.text+0x5a5): undefined reference to `gg_panl_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:137:(.text+0x5ef): undefined reference to `im_lutf_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:138:(.text+0x5f7): undefined reference to `im_drop_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:160:(.text+0x6d9): undefined reference to `gr_titl_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:164:(.text+0x726): undefined reference to `gg_wstr_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids/gpnids.f:174:(.text+0x759): undefined reference to `gg_cbar_'
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gemlib.a(ipgtpt.o): in function `ip_gtpt_':
/home/gempak/GEMPAK7/gempak/source/gemlib/ip/ipgtpt.f:103:(.text+0x196): undefined reference to `gg_zare_'
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gemlib.a(ipinit.o): in function `ip_init_':
/home/gempak/GEMPAK7/gempak/source/gemlib/ip/ipinit.f:37:(.text+0x18): undefined reference to `in_bdta_'
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gemlib.a(iplutf.o): in function `ip_lutf_':
/home/gempak/GEMPAK7/gempak/source/gemlib/ip/iplutf.f:32:(.text+0x39): undefined reference to `im_lutf_'
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gplt.a(gsmode.o): in function `gsmode_':
/home/gempak/GEMPAK7/gempak/source/gplt/access/gsmode.f:39:(.text+0x34): undefined reference to `updpxy_'
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gplt.a(gclear.o): in function `gclear_':
/home/gempak/GEMPAK7/gempak/source/gplt/control/gclear.f:73:(.text+0xc0): undefined reference to `updsxy_'
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gplt.a(gtrans.o): in function `gtrans_':
/home/gempak/GEMPAK7/gempak/source/gplt/transform/gtrans.f:147:(.text+0x3b8): undefined reference to `prnlon_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/gplt/transform/gtrans.f:138:(.text+0x507): undefined reference to `prnlon_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/gplt/transform/gtrans.f:161:(.text+0x54e): undefined reference to `prnlon_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/gplt/transform/gtrans.f:176:(.text+0x598): undefined reference to `prnlon_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/gplt/transform/gtrans.f:211:(.text+0x736): undefined reference to `prnlon_'
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gplt.a(gtrans.o):/home/gempak/GEMPAK7/gempak/source/gplt/transform/gtrans.f:226: more undefined references to `prnlon_' follow
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gplt.a(gsattr.o): in function `gsattr_':
/home/gempak/GEMPAK7/gempak/source/gplt/attribute/gsattr.f:83:(.text+0x4ce): undefined reference to `updsxy_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/gplt/attribute/gsattr.f:169:(.text+0x633): undefined reference to `gsatmg4_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/gplt/attribute/gsattr.f:174:(.text+0x70c): undefined reference to `gsatmg_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/gplt/attribute/gsattr.f:187:(.text+0x7c0): undefined reference to `gsgraf_'
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gplt.a(gsmprj.o): in function `gsmprj_':
/home/gempak/GEMPAK7/gempak/source/gplt/map/gsmprj.f:163:(.text+0x163): undefined reference to `updmap_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/gplt/map/gsmprj.f:164:(.text+0x17b): undefined reference to `updpxy_'
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gplt.a(gconml.o): in function `gconml_':
/home/gempak/GEMPAK7/gempak/source/gplt/transform/gconml.f:56:(.text+0xa8): undefined reference to `prnlon_'
/usr/bin/ld: /home/gempak/GEMPAK7/os/linux64/lib/gplt.a(gcylml.o): in function `gcylml_':
/home/gempak/GEMPAK7/gempak/source/gplt/transform/gcylml.f:110:(.text+0x21b): undefined reference to `prnlnr_'
/usr/bin/ld: /home/gempak/GEMPAK7/gempak/source/gplt/transform/gcylml.f:112:(.text+0x241): undefined reference to `prnlnr_'
collect2: error: ld returned 1 exit status
make[6]: *** [Makefile:120: gpnids_gf] Error 1
make[6]: Leaving directory '/home/gempak/GEMPAK7/gempak/source/programs/upc/programs/gpnids'
make[5]: Leaving directory '/home/gempak/GEMPAK7/gempak/source/programs/upc/programs'
make[4]: Leaving directory '/home/gempak/GEMPAK7/gempak/source/programs/upc'
making programs_gf in /home/gempak/GEMPAK7/gempak/source/programs/dc
make[4]: Entering directory '/home/gempak/GEMPAK7/gempak/source/programs/dc'
Nothing to make for programs_nc in decoders
make[4]: Leaving directory '/home/gempak/GEMPAK7/gempak/source/programs/dc'
make[3]: Leaving directory '/home/gempak/GEMPAK7/gempak/source/programs'
make[2]: Leaving directory '/home/gempak/GEMPAK7/gempak/source'
making programs_gf in /home/gempak/GEMPAK7/gempak/maps/programs
make[2]: Entering directory '/home/gempak/GEMPAK7/gempak/maps/programs'
Nothing to make for programs_gf in gui
make[2]: Leaving directory '/home/gempak/GEMPAK7/gempak/maps/programs'
making programs_gf in /home/gempak/GEMPAK7/gempak/utilities
make[2]: Entering directory '/home/gempak/GEMPAK7/gempak/utilities'
Nothing to make for programs_gf in utilities
make[2]: Leaving directory '/home/gempak/GEMPAK7/gempak/utilities'
make[1]: Leaving directory '/home/gempak/GEMPAK7/gempak'

Can anyone offer any hints as to what is happening? This is on a fresh install of Linux. He says he has everything installed that the instructions tell him to...

**Comment by ktyle** [comment]
@sebenste could you or your colleage attach the full log of the installation? It looks like several individual functions in the underlying libraries did not compile.

I haven't tried with Ubuntu 24.04, but with some trial and error have gotten it to fully compile on Fedora 40 (Apple Silicon, that's another story ... )

**Comment by sgdecker** [comment]
GEMPAK compiles for me. Are the libtool and autoconf packages installed?

**Comment by sebenste** [comment]
Hello sgdecker,

Yes, they are installed.

Kevin: Here is a copy of the make.txt file.[make.txt](https://github.com/user-attachments/files/17468793/make.txt)

**Comment by mzuranski** [comment]
Those errors (and others within the above log) are indicative of the `-fallow-invalid-boz -fallow-argument-mismatch` arguments not being passed.  At a glance it looks like they are, but the log confirms they are not:
`gfortran -fno-second-underscore -fno-range-check -fd-lines-as-comments -I/home/gempak/GEMPAK7/gempak/include -I/home/gempak/GEMPAK7/os/linux64/include -g -O  `


What shell is the user running this under (bash, csh, etc.)?
What are the full contents of the Gemenviron(.profile) file?
After sourcing that file, what is the output of `env`?

And just for grins, what is the output of `uname -a` and `lsb_release -a`?

**Comment by sebenste** [comment]
He's using tcsh.

home/gempak/GEMPAK7]# uname -a
Linux batman3 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


[gempak@batman3 /home/gempak/GEMPAK7]# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

[env_output1.docx](https://github.com/user-attachments/files/17484712/env_output1.docx)


I get an error message trying to upload his .gemenviron file, I'll try that tomorrow.

**Comment by sebenste** [comment]
[gemenviron.docx](https://github.com/user-attachments/files/17484730/gemenviron.docx)

Gemenviron file.

**Comment by sebenste** [comment]
[env_output1.docx](https://github.com/user-attachments/files/17484816/env_output1.docx)

Does that work?

**Comment by sebenste** [comment]
[gempak@batman3 /home/gempak/GEMPAK7]# env
AFOS_ALARMS=/home/gempak/nawips/metdat/alarms/
BGRUVN=/home/gempak/bufrgruven
CLUTTER_IM_MODULE=ibus
COLORFGBG=15;0
COLORTERM=truecolor
CONFIGDIR=/home/gempak/GEMPAK7/config
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=plasma
DISPLAY=:0
Dmaster=/home/gempak/Dmaster
EDEX_SERVER=[edex-cloud.unidata.ucar.edu](http://edex-cloud.unidata.ucar.edu/)
GEMDATA=/home/ldm/data
GEMERR=/home/gempak/GEMPAK7/gempak/error
GEMEXE=/home/gempak/GEMPAK7/os/linux64/bin
GEMGTXT=/home/gempak/GEMPAK7/gempak/txt/gemlib
GEMHLP=/home/gempak/GEMPAK7/gempak/help
GEMLIB=/home/gempak/GEMPAK7/os/linux64/lib
GEMMAPS=/home/gempak/GEMPAK7/gempak/maps
GEMNTS=/home/gempak/GEMPAK7/gempak/nts
GEMPAK=/home/gempak/GEMPAK7/gempak
GEMPAKHOME=/home/gempak/GEMPAK7/gempak
GEMPARM=/home/gempak/GEMPAK7/gempak/parm
GEMPDF=/home/gempak/GEMPAK7/gempak/pdf
GEMPTXT=/home/gempak/GEMPAK7/gempak/txt/programs
GEMTBL=/home/gempak/GEMPAK7/gempak/tables
GEM_COMPTYPE=gfortran
GMASTER=/home/gempak/gribmaster2.1
GOES16=/home/gempak/nawips/metdat/images/sat/GOES16
GOES17=/home/gempak/nawips/metdat/images/sat/GOES17
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GRIB=/home/gempak/nawips/gempak/grib
GROUP=gempak
GRPHGD=/home/gempak
GSM_SKIP_SSH_AGENT_WORKAROUND=true
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/gempak/.gtkrc-2.0:/home/gempak/.config/gtkrc-2.0
GTK_IM_MODULE=ibus
GTK_MODULES=gail:atk-bridge
GTK_RC_FILES=/etc/gtk/gtkrc:/home/gempak/.gtkrc:/home/gempak/.config/gtkrc
HDS=/home/gempak/nawips/metdat/gempak/grids
HOME=/home/gempak
HOST=batman3
HOSTTYPE=x86_64-linux
IM_CONFIG_PHASE=1
INVOCATION_ID=109846d069724136a8e33b49b28bdf2b
JOURNAL_STREAM=8:9928
KDE_APPLICATIONS_AS_SCOPE=1
KDE_FULL_SESSION=true
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=5
KONSOLE_DBUS_SERVICE=:1.75
KONSOLE_DBUS_SESSION=/Sessions/3
KONSOLE_VERSION=230805
LANG=en_US.UTF-8
LANGUAGE=
LC_ADDRESS=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
LDMDATA=/home/ldm/data
LDMHOME=/home/gempak
LD_LIBRARY_PATH=/home/gempak/GEMPAK7/os/linux64/lib:/home/gempak/GEMPAK7/os/linux64/lib:/home/gempak/GEMPAK7/os/linux64/lib
LOGNAME=gempak
LP=lp -c
LPFLAG=-d
MACHTYPE=x86_64
MAKEINC=Makeinc.common
MANAGERPID=1839
MANPATH=/home/gempak/man:/usr/share/man
MEL_BUFR=/home/gempak/GEMPAK7/extlibs/melBUFR/melbufr
MEL_BUFR_TABLES=/home/gempak/GEMPAK7/gempak/tables/melbufr
MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/plasma-ksmserver.service/memory.pressure
MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
METDAT=/home/gempak/nawips/metdat
MODEL=/home/gempak/nawips/metdat/gempak/grids
MODEL_SFC=/home/gempak/nawips/metdat/modsnd/gempak/bufr/model
MODEL_SND=/home/gempak/nawips/metdat/modsnd/gempak/bufr/model
NAWIPS=/home/gempak/GEMPAK7
NA_OS=linux64
NEXCOMP=/home/gempak/nawips/metdat/images/sat/NEXRCOMP
NHEMMULTI_IR=/home/gempak/nawips/metdat/images/sat/NHEM-MULTICOMP/1km/IR
NLDN=/home/gempak/nawips/metdat/nldn
NLSPATH=/usr/share/locale/%L/LC_MESSAGES/%N.cat:/usr/share/locale/%l/LC_MESSAGES/%N.cat
NMAP_RESTORE=/home/gempak/GEMPAK7/gempak/nts/nmap/restore
NTRANS_META=/home/gempak/nawips/metdat/meta
OBS=/home/gempak/nawips/metdat
OS=linux64
OSTYPE=linux
OS_BIN=/home/gempak/GEMPAK7/os/linux64/bin
OS_INC=/home/gempak/GEMPAK7/os/linux64/include
OS_LIB=/home/gempak/GEMPAK7/os/linux64/lib
OS_ROOT=/home/gempak/GEMPAK7/os/linux64
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
PAPERSIZE=letter
PATH=/home/gempak/bin:/home/gempak/decoders:/home/gempak/util:/home/gempak/bin:/home/gempak/.bin:/usr/X11R6/bin:/home/gempak/bin:/home/gempak/decoders:/home/gempak/util:/home/gempak/bin:/home/gempak/.bin:/usr/X11R6/bin:/usr/local/sbin:/
usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/gempak/GEMPAK7/os/linux64/bin:/home/gempak/GEMPAK7/bin:/home/gempak/gribmaster2.1:/home/gempak/gribmaster5:/home/gempak/webpage_scripts:/home/gempak
/bufrgruven:/home/gempak/nawips/exe/linux/sfcoa:/home/gempak/nawips/exe/linux/sfcoa/larry:/home/gempak/GEMPAK7/os/linux64/bin:/home/gempak/GEMPAK7/bin:/home/gempak/gribmaster2.1:/home/gempak/gribmaster5:/home/gempak/webpage_scripts:/hom
e/gempak/bufrgruven:/home/gempak/nawips/exe/linux/sfcoa:/home/gempak/nawips/exe/linux/sfcoa/larry:/home/gempak/GEMPAK7/os/linux64/bin:/home/gempak/GEMPAK7/bin
PROFILEHOME=
PWD=/home/gempak/GEMPAK7
PYTHONPATH=/home/gempak/GEMPAK7/scripts/python:/home/gempak/GEMPAK7/scripts/python:/home/gempak/GEMPAK7/scripts/python
QTWEBENGINE_DICTIONARIES_PATH=/usr/share/hunspell-bdic/
QT_ACCESSIBILITY=1
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_IM_MODULE=ibus
RAD=/home/gempak/nawips/metdat/nexrad
RAW_SAO=/home/ldm/data/surface/sao
RAW_SYN=/home/ldm/data/surface/syn
RAW_UPA=/home/ldm/data/upperair
RBKGPH=/home/gempak/nawips/metdat/redbook
RTDATA=/home/gempak/gribmaster2.1
SAO=/home/gempak/nawips/metdat/surface
SAT=/home/gempak/nawips/metdat/images/sat
SESSION_MANAGER=local/batman3:@/tmp/.ICE-unix/2191,unix/batman3:/tmp/.ICE-unix/2191
SHELL=/usr/bin/tcsh
SHELL_SESSION_ID=5deb23ffaa194c7ea465c55cdb70f75b
SHLVL=2
SIGWX=/home/gempak/nawips/metdat/sigwx
SPDATA=/home/gempak/nawips/metdat
SSH_AGENT_PID=2010
SSH_ASKPASS=/usr/bin/ksshaskpass
SSH_AUTH_SOCK=/tmp/ssh-t8l3iEnY3z4m/agent.1930
SUPER_NATIONAL_IR=/home/gempak/nawips/metdat/images/sat/SUPER-NATIONAL/8km/IR
SYSTEMD_EXEC_PID=2191
TERM=xterm-256color
TEST_DATA=/home/gempak/GEMPAK7/gempak/data
TEXT_DATA=/home/gempak/nawips/metdat/nwx
TEXT_WARN=/home/gempak/nawips/metdat/nwx/watch_warn
TORN_WARN=/home/gempak/nawips/metdat/nwx/watch_warn/TOR
TSTRM_WARN=/home/gempak/nawips/metdat/nwx/watch_warn/SVR
UPA=/home/gempak/nawips/metdat/upperair
USER=gempak
VENDOR=unknown
WINDOWID=52428813
XAUTHORITY=/tmp/xauth_enHDCa
XCURSOR_SIZE=24
XCURSOR_THEME=breeze_cursors
XDG_CONFIG_DIRS=/home/gempak/.config/kdedefaults:/etc/xdg/xdg-plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings
XDG_CURRENT_DESKTOP=KDE
XDG_DATA_DIRS=/usr/share/plasma:/usr/local/share/:/usr/share/
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_ID=3
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_SESSION_TYPE=x11
XDG_VTNR=2
XMODIFIERS=@im=ibus
XUSERFILESEARCHPATH=/home/gempak/GEMPAK7/resource/%N:/home/gempak/GEMPAK7/resource/%N:/home/gempak/GEMPAK7/resource/%N
[gempak@batman3 /home/gempak/GEMPAK7]#

**Comment by mzuranski** [comment]
Okay thanks.  What about the output of `ls -l` of that Makefile dir?  

My theory at the moment is what you have pasted at the top of the issue isn't being referenced.  So I'd be curious to know how it is intended to be referenced.

**Comment by sebenste** [comment]
gempak@batman3 /home/gempak/GEMPAK7/config]# ls -1
buildmacro.csh*
Makeinc.aix
Makeinc.common@
Makeinc.common_linux
Makeinc.common_sol
Makeinc.cygwin
Makeinc.darwin
Makeinc.freebsd
Makeinc.hpux
Makeinc.hpux_gcc
Makeinc.irix
Makeinc.linux
Makeinc.linux64
Makeinc.linux64_g77
Makeinc.linux64_gfortran
Makeinc.linux64_gfortran_fedora
Makeinc.linux64_gfortran_ubuntu
Makeinc.linux_g77
Makeinc.linux_gfortran
Makeinc.linux_gfortran_fedora
Makeinc.linux_gfortran_ubuntu
Makeinc.linux_pgi
Makeinc.osf
Makeinc.sol
Makeinc.sol_gcc
Makeinc.x86
[gempak@batman3 /home/gempak/GEMPAK7/config]#

**Comment by sebenste** [comment]
I asked him to try to compile it under bash instead of tcsh. It failed with these errors.![Image](https://github.com/user-attachments/assets/00ae2a92-9502-4d53-b357-6588880b0fc3)
![Image](https://github.com/user-attachments/assets/37158d5e-52b5-400c-945e-1d82d38b2bd5)

**Comment by sebenste** [comment]
ls -1 command in the $NAWIPS/config directory....

gempak@batman3:~/GEMPAK7/config$ ls -1
buildmacro.csh
Makeinc.aix
Makeinc.common
Makeinc.common_linux
Makeinc.common_sol
Makeinc.cygwin
Makeinc.darwin
Makeinc.freebsd
Makeinc.hpux
Makeinc.hpux_gcc
Makeinc.irix
Makeinc.linux
Makeinc.linux64
Makeinc.linux64_g77
Makeinc.linux64_gfortran
Makeinc.linux64_gfortran_fedora
Makeinc.linux64_gfortran_ubuntu
Makeinc.linux_g77
Makeinc.linux_gfortran
Makeinc.linux_gfortran_fedora
Makeinc.linux_gfortran_ubuntu
Makeinc.linux_pgi
Makeinc.osf
Makeinc.sol
Makeinc.sol_gcc
Makeinc.x86
gempak@batman3:~/GEMPAK7/config$


On Wed, Oct 23, 2024 at 3:52 AM Kevin Polston <[kevin.polston](mailto:kevin.polston)> wrote:
[gempak@batman3 /home/gempak/GEMPAK7/config]# ls -1
buildmacro.csh*
Makeinc.aix
Makeinc.common@
Makeinc.common_linux
Makeinc.common_sol
Makeinc.cygwin
Makeinc.darwin
Makeinc.freebsd
Makeinc.hpux
Makeinc.hpux_gcc
Makeinc.irix
Makeinc.linux
Makeinc.linux64
Makeinc.linux64_g77
Makeinc.linux64_gfortran
Makeinc.linux64_gfortran_fedora
Makeinc.linux64_gfortran_ubuntu
Makeinc.linux_g77
Makeinc.linux_gfortran
Makeinc.linux_gfortran_fedora
Makeinc.linux_gfortran_ubuntu
Makeinc.linux_pgi
Makeinc.osf
Makeinc.sol
Makeinc.sol_gcc
Makeinc.x86
[gempak@batman3 /home/gempak/GEMPAK7/config]#

**Comment by mzuranski** [comment]
In the original post you gave the contents of the Makeinc.linux64_gfortran_ubuntu file.  How is that file being used?  I don't see any symlinks here, which normally I would expect there to be.  Otherwise Makeinc.linux64_gfortran is used (iirc).  Did a step get skipped?

**Comment by sebenste** [comment]
He says he didn't skip a step.

**Comment by sebenste** [comment]
and he's wondering if you have the instructions and how exactly you got it to compile. He's followed them to a "T", but he just keeps getting the same errors.

**Comment by mzuranski** [comment]
Make sure `Makeinc.linux64_gfortran_ubuntu` is symlinked correctly.  It seems to me at least that this file is not being referenced like it should be.

**Comment by akrherz** [comment]
The steps for [Github CI on ubuntu](https://github.com/Unidata/gempak/blob/c39de8bfef41b9528f80f69464c65adda8a0f5ec/.github/workflows/main.yml#L14-L21) are rather limited

**Comment by sebenste** [comment]
I got confirmation that a step was skipped in this from a third party, so I am going to close this ticket. Sorry for the trouble.
