### ISSUE TITLE
gempak/tables/nwx/master.tbl references unset TEXT_DATA2 variable

### ISSUE THREAD

**Issue by akrherz** [Unidata/gempak#34]
The `gempak/tables/nwx/master.tbl` file references a variable `TEXT_DATA2`.  Is this some sort of one-off that sneaked into the codebase?  Shouldn't it just be `TEXT_DATA` ?  I can PR it, if so.

**Comment by ktyle** [comment]
The only file in which this text string exists is in gempak/tables/nwx/master.tbl, so let's get rid of that stray 2!
