### ISSUE TITLE
The fix for the Y2K Bug has expired. I propose a new fix that will highlight a future issue.

### ISSUE THREAD

**Issue by ClariNerd617** [Unidata/gempak#50]
This is for gempak:latest.

In https://github.com/Unidata/gempak/blob/master/gempak/source/gemlib/ti/tiyy24.f

the code only supports conversion of 2-digit dates up to 20 to be in the 21st century, so if it runs now, it will read the current year as 1921.

there are two solutions I can think of: 

1.  convince the entire meteorological community to only use ISO-8601 format for date-time.
2. bump the year of expiry out to 2038, when the 32-bit integer storing epoch time runs out of values. that way, when we inevitably forget to fix both this issue and that one, we can fix both at once (hopefully)!

**Comment by akrherz** [comment]
Please see current discussions on [gembud](https://www.unidata.ucar.edu/mailing_lists/archives/gembud/2021/thread.html).  Eventually, the Unidata GEMPAK will get updated to the [NCEP GEMPAK](https://www.nco.ncep.noaa.gov/sdb/nawips/distribution/), which is generally what this code repo tracks.
