### ISSUE TITLE
Assessment of log4j vulnerabilities

### ISSUE THREAD

**Issue by akrherz** [Unidata/gempak#59]
"Oh, GEMPAK is ancient FORTRAN code from last century and would not contain java log4j" ...  Well, not quite.

There are some `a2conv` utilities in Java that utilize log4j ... but they are using an ancient log4j circa 1.2.16

At this time, it is unclear if GEMPAK is actually vulnerable to any of the recent log4j vulnerabilities.  GEMPAK development is generally stalled out and these utilities are likely not used by Unidata partners...

So I figured I would at least post this placeholder and further boggle a path forward on this.

**Comment by mzuranski** [comment]
Commenting purely to say the following:

When I heard about log4j I had the same reaction and found the same thing.  My immediate thought was _The only other person who would ever notice this is @akrherz, and I'm sure he would have found it before me._  Happy New Year, sir!
