### ISSUE TITLE
BUG: Some GEMPAK tables appear to be missing, but we don't know which ones

### ISSUE THREAD

**Issue by sebenste** [Unidata/gempak#68]
Daryl,

A friend of mine and I have confirmed that some derived model products in GEMPAK are not working under 7.14, but were under 7.5.

Known: HRRR and NAMNEST reflectivity and updraft helicity will not plot. When they did on the command line, it used 3 different tables under 7.5. It now only finds two, and we get a bunch of GB-1 and GB-16 (I think) errors that a grid is not found in 7.14. Unfortunately, we didn't note which one was missing, because two servers got updated simultaneously.

Is there any way you can cross-check to see if any GEMPAK grid tables or soft links are missing?

**Comment by akrherz** [comment]
Thanks @sebenste , so I suspect the issue is not that tables are missing as my merging of NCEP NAWIPS did not remove any Unidata GEMPAK Tables, but that I overwrote important tables that I should not have.  For example, #64 .  It is just a matter of investigating this and fixing it.  Knowing exactly where the issue is, is the hardest part of the fix.

**Comment by akrherz** [comment]
@sebenste I need more to go on here.  Are the reflectivity fields found in the GEMPAK grid files?   The issue could be the `dcgrib` step of writing the grib data into the GEMPAK grid files and/or the step of the GEMPAK GUI not knowing how to find the field in the file?

**Comment by sebenste** [comment]
He's not seeing the REFD (Reflectivity) files, nor is he seeing the updraft helicity files. He was under 7.5. No changes were made to pqact.

**Comment by sebenste** [comment]
![43074869-690C-4C84-BC92-98579E93D2FC](https://user-images.githubusercontent.com/22505321/156039497-607d8a3d-b647-42bd-b877-b1a5a0c21cb7.jpeg)

**Comment by sebenste** [comment]
"This shows up as my script to decode the HRRR files goes by. This is using gdinfo on the hrrrr files. There should be a level that says 1000 0 HGHT REFD"

**Comment by sebenste** [comment]
"And a couple other levels like 4000 (which I believe is the composite Reflectivity) and also a mxuphl parameter at levels 2000 5000 hght and also 1000 I believe for the updraft helicity.

I also think on the HRRR model there should be a 3000 0 HGHT CAPE  parameter to show the 0-3 km CAPE.  I never saw that in the NAMNEST but it was in the HRRR.

So, there are a few parameters at least that aren't showing up."

**Comment by akrherz** [comment]
So this look like trouble, on current main branch
```
gempak/tables (main) $ git grep REFD
grid/g2varsncepwww.tbl:000 016 004 000 Reflectivity                     dB                   REFD             0  -9999.00
grid/g2varsncepwww.tbl:000 016 195 000 Reflectivity                     dB                   REFD             0  -9999.00
grid/ncepgrib129.tbl:211 Reflectivity                      dbZ                  REFD             0  -9999.00       0         0
```

on 7.5.1 tag
```
gempak/tables ((HEAD detached at 7.5.1)) $ git grep REFD
grid/g2varsncep1.tbl:000 016 004 000 Reflectivity                     dB                   REFD             0  -9999.00
grid/g2varsncep1.tbl:000 016 195 000 reflectivity                     dB                   REFD             0  -9999.00
grid/g2varsncep1.tbl:000 016 195 002 reflectivity                     dB                   REFD             0  -9999.00
grid/g2varsncepwww.tbl:000 016 004 000 Reflectivity                     dB                   REFD             0  -9999.00
grid/g2varsncepwww.tbl:000 016 195 000 Reflectivity                     dB                   REFD             0  -9999.00
grid/g2varswmo2.tbl:000 016 004 000 Reflectivity                     dB                   REFD             0  -9999.00
grid/ncepgrib129.tbl:211 Derived radar reflectivity        dbZ                  REFD             0  -9999.00       0         0
```

**Comment by mzuranski** [comment]
> I also think on the HRRR model there should be a 3000 0 HGHT CAPE parameter to show the 0-3 km CAPE. I never saw that in the NAMNEST but it was in the HRRR.

Just putting this out there:  0-3 km CAPE should be present for the HRRR and RAP, but those should be the only two NCEP models that will have that for now.

**Comment by sebenste** [comment]
That addresses the reflectivity, but doesn't addreses the helicity issue.

**Comment by akrherz** [comment]
@sebenste have you tested my PR to see if it fixes it?

**Comment by sebenste** [comment]
![10C19CA5-0025-4966-A421-C9F1FAF4C89F](https://user-images.githubusercontent.com/22505321/156062424-ad42f7d9-5a6c-4678-8f9a-675c22189f4f.jpeg)

"You'll notice at the top there's the  263 TMPL REFD ; 0:3000 HGHT CAPE is there now too; and the 4000 and  1000 0 HGHT REFD. It worked! Updraft helicity still does not work, but this is a big improvement."

**Comment by akrherz** [comment]
Thanks, I took the PR, and am now hunting for updraft helicity (`UPHL`).

**Comment by akrherz** [comment]
So as a test, I downloaded the 0z hrr and jammed it through `dcgrib2`.  `gdinfo` reports then the following fields of interest
```
 26     220228/0000F001                       5000  2000   HGHT MXUPHL01   
 28     220228/0000F001                       3000  0      HGHT MXUPHL01   
 30     220228/0000F001                       2000  0      HGHT MXUPHL01  
```

Are those it?

**Comment by sebenste** [comment]
"Yes. Those are exactly what I want to see!"

**Comment by akrherz** [comment]
> "Yes. Those are exactly what I want to see! The 2-5km; 0-3 km; and 0-2km updraft helicity!"

OK, so it should be working now with a current `main` branch build of GEMPAK.  That's what I ran my test above with.

**Comment by sebenste** [comment]
OK. Could you do me a favor and please kindly post the grids here, like you did above?

Also, is there a chance that there are more missing ones?

**Comment by akrherz** [comment]
I just wget this [grib file](https://ftpprd.ncep.noaa.gov/data/nccf/com/hrrr/prod/hrrr.20220228/conus/hrrr.t00z.wrfsfcf01.grib2) and `cat file.grib2 | dcgrib test.gem`

**Comment by sebenste** [comment]
So I saw the link to download the release on the main page and it says 404 not found. I also don't see where you can download the individual tables from Github. How do I do it?

**Comment by sebenste** [comment]
![Uploading 0710097A-93CA-44C5-9CBC-64C93E8F13A9.jpeg…]()

**Comment by sebenste** [comment]
Updraft helicity for the HRRR is still not working.

**Comment by sebenste** [comment]
OK, never mind, operator error....the grib tables work! But the download link is still broken. I'll close this ticket as that should be a separate issue. Thanks for all of your help today! Have a good night.
