### ISSUE TITLE
Enhancement: Support base reflectivity and enhanced echo top products in MRMS

### ISSUE THREAD

**Issue by sebenste** [Unidata/gempak#87]
If, and I repeat, if this can be done with GEMPAK table additions, they would be most welcomed.

**Comment by sebenste** [comment]
Base reflectivity; LVL3 HREET; MergedRhoHV; and LVL3_HighResVIL.

**Comment by sebenste** [comment]
Excellent. Closing this ticket.

**Comment by akrherz** [comment]
You are welcome, but we need to leave this open until I get this merged into GEMPAK.

**Comment by sebenste** [comment]
Gotcha, thanks! We will be testing it probably tonight.
